### ISSUE TITLE
Problem building spilo with podman

### ISSUE THREAD

**Issue by sasadangelo** [zalando/spilo#782]
Hi all,

I have podman 4.2.1 (latest release) installed on my Mac with:
```
brew install podman
podman machine init
podman machine start
```

I have this variable in my .bash_profile:
```
export BUILDAH_FORMAT=docker
```

then I built the latest version of the spilo image with the command:
```
cd spilo/postgres-appliance
podman build . --build-arg PGVERSION=11 --build-arg PGOLDVERSIONS="" --tag spilo:latest
```

I got the following problem:
```
[4/4] STEP 1/19: FROM builder-false
Resolving "builder-false" using unqualified-search registries (/etc/containers/registries.conf.d/999-podman-machine.conf)
Trying to pull docker.io/library/builder-false:latest...
Error: error creating build container: initializing source docker://builder-false:latest: reading manifest latest in docker.io/library/builder-false: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

The problem is on this line:
https://github.com/zalando/spilo/blob/569524be789a7b72ab66d6e86d5303f55f00c5a6/postgres-appliance/Dockerfile#L488

if you replace this:
```
FROM builder-${COMPRESS}
```

with this:
```
FROM builder-false.    (or builder-true)
```

it works. It also works if you use the command:
```
cd spilo/postgres-appliance
podman build . --build-arg PGVERSION=11 --build-arg PGOLDVERSIONS="" --build-arg COMPRESS="false" --tag spilo:latest
```

With docker (that we have in our official build system) everything works. However, for licensing problem my organization for local development suggest us to use podman. It's not clear to me the reason of this failure and why COMPRESS variable give this issue.

**Comment by hughcapet** [comment]
I have the same issue and it is not clear for me either. I haven't time yet to dig into this but since I am not the only one who experiences it, I should probably do it in the near future.

**Comment by hughcapet** [comment]
Seems that [this PR](https://github.com/containers/buildah/pull/4366) should fix the problem

**Comment by sasadangelo** [comment]
Hi @hughcapet and @CyberDem0n,

Today I build locally on my Mac spilo at the latest version on branch master but the problem is still there.
The PR was perged in Nov 22 2022 so I expected it is included.
I think the local build without the build-args doesn't work properly.

Here what I did:
```
git clone https://github.com/zalando/spilo
cd spilo/postgres-appliance
docker build . --build-arg PGVERSION="11" --build-arg PGOLDVERSIONS=""  --tag spilo:2.1-p9
```

I get the error mentioned in the first message. The only way to fix it is to run:
```
docker build . --build-arg PGVERSION="11" --build-arg PGOLDVERSIONS=""  --tag spilo:2.1-p9 --build-arg COMPRESS="false"
```

**Comment by hughcapet** [comment]
Yes, I was wrong stating this is the PR we need.
Looks someone even created an issue in podman repo after facing this issue in Spilo
https://github.com/containers/podman/issues/17085

**Comment by hughcapet** [comment]
The problem is fixed in Podman 4.4.1
